### ISSUE TITLE
具体参数能说说吗？

### ISSUE THREAD

**Issue by hungryandfoolishboy** [WXR1998/taobao_guess_price_2022#1]
具体参数能说说吗？

**Comment by hungryandfoolishboy** [comment]
raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by WXR1998** [comment]
这个问题我没遇到过，能给出更详细的上下文吗

**Comment by hungryandfoolishboy** [comment]
WARNING:easyocr.easyocr:Downloading recognition model, please wait. This may take several minutes depending upon your network connection.
Progress: |▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒| 100.0% CompleteTraceback (most recent call last):
  File "C:\Users\Leonardo\Desktop\taobao_guess_price_2022-master\main.py", line 30, in <module>
    sku_list = ocr.get_sku_list(os.path.join(config.input_image_path, input_filename))
  File "C:\Users\Leonardo\Desktop\taobao_guess_price_2022-master\ocr.py", line 37, in get_sku_list
    decoder = easyocr.Reader(['ch_sim', 'en'])
  File "D:\▒▒▒▒▒ļ▒\python\lib\site-packages\easyocr\easyocr.py", line 174, in __init__
    download_and_unzip(model['url'], model['filename'], self.model_storage_directory, verbose)
  File "D:\▒▒▒▒▒ļ▒\python\lib\site-packages\easyocr\utils.py", line 586, in download_and_unzip
    urlretrieve(url, zip_path, reporthook=reporthook)
  File "D:\▒▒▒▒▒ļ▒\python\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "D:\▒▒▒▒▒ļ▒\python\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\▒▒▒▒▒ļ▒\python\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "D:\▒▒▒▒▒ļ▒\python\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\▒▒▒▒▒ļ▒\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\▒▒▒▒▒ļ▒\python\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\▒▒▒▒▒ļ▒\python\lib\urllib\request.py", line 1352, in do_open
    r = h.getresponse()
  File "D:\▒▒▒▒▒ļ▒\python\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "D:\▒▒▒▒▒ļ▒\python\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "D:\▒▒▒▒▒ļ▒\python\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by WXR1998** [comment]
这个是easyocr的锅，下载它需要的pre-trained model的时候需要挂代理才能下，只需要第一次运行的时候下载，后面就可以使用缓存了

**Comment by hungryandfoolishboy** [comment]
我等下挂全局代理试试，这个跑的速度快么,不要时间结束了，识别还没出来的😂

**Comment by WXR1998** [comment]
我的电脑没有gpu的情况下只需要4秒左右就能出结果，有gpu可以更快

**Comment by hungryandfoolishboy** [comment]
ok，可以了，谢谢。

**Comment by hungryandfoolishboy** [comment]
start一下
